networks:
  frontend:
    external: true
    
services:
  gitea:
    image: docker.gitea.com/gitea:nightly
    container_name: gitea
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=${TZ}
      - USER_UID=${PUID}
      - USER_GID=${GUID}
    restart: always
    networks:
      - frontend
    volumes:
      - ${BASE_PATH}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
