networks:
  frontend:
    external: true

volumes:
  gotify-data:

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    ports:
      - 8099:80
    env_file:
      - stack.env
    volumes:
      - gotify-data:/app/data
    networks:
      - frontend
