networks:
  frontend:
    external: true
  backend_tandoor:
    external: true
    
services:
  db_recipes:
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - ${BASE_PATH}/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - stack.env
    networks:
      - backend_tandoor

  web_recipes:
    restart: unless-stopped
    image: vabene1111/recipes:latest
    container_name: tandoor
    env_file:
      - stack.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - ${BASE_PATH}/tandoor/mediafiles:/opt/recipes/mediafiles
    ports:
      - "9876:80"
    depends_on:
      - db_recipes
    networks:
      - frontend
      - backend_tandoor


volumes:

  staticfiles:
